export const SET_CURRENT_CALENDAR = "SET_CURRENT_CALENDAR";
export const SET_USER_CALENDARS = "SET_USER_CALENDARS";
export const SET_CALENDAR_USERS = "SET_CALENDAR_USERS";
export const REMOVE_CALENDAR = "REMOVE_CALENDAR";
export const ADD_CALENDAR="ADD_CALENDAR";
export const SET_CALENDAR_EVENTS="SET_CALENDAR_EVENTS";

