// <auto-generated />
using System;
using CalendarApp.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CalendarApp.Context.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20240403075646_db_relationships")]
    partial class dbrelationships
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Repository.Entities.Calender", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DirectorId")
                        .HasColumnType("int");

                    b.Property<string>("GroupName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SiteUserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DirectorId");

                    b.HasIndex("SiteUserId");

                    b.ToTable("Calenders");
                });

            modelBuilder.Entity("Repository.Entities.CalenderUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CalenderId")
                        .HasColumnType("int");

                    b.Property<int>("DescendantId")
                        .HasColumnType("int");

                    b.Property<string>("UserType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CalenderId");

                    b.HasIndex("DescendantId")
                        .IsUnique();

                    b.ToTable("CalenderUsers");
                });

            modelBuilder.Entity("Repository.Entities.CalenderYear", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CalenderId")
                        .HasColumnType("int");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CalenderId");

                    b.ToTable("CalenderYears");
                });

            modelBuilder.Entity("Repository.Entities.Descendant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("BornDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("FatherID")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("MotherID")
                        .HasColumnType("int");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SiteUserId")
                        .HasColumnType("int");

                    b.Property<int?>("SpouseID")
                        .HasColumnType("int");

                    b.Property<int>("TZ")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FatherID")
                        .IsUnique()
                        .HasFilter("[FatherID] IS NOT NULL");

                    b.HasIndex("MotherID")
                        .IsUnique()
                        .HasFilter("[MotherID] IS NOT NULL");

                    b.HasIndex("SiteUserId");

                    b.HasIndex("SpouseID")
                        .IsUnique()
                        .HasFilter("[SpouseID] IS NOT NULL");

                    b.ToTable("Descendants");
                });

            modelBuilder.Entity("Repository.Entities.Event", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CalenderId")
                        .HasColumnType("int");

                    b.Property<int>("DescendantId")
                        .HasColumnType("int");

                    b.Property<string>("EventType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EventYear")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HebrewDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("OneTimeEvent")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("CalenderId");

                    b.HasIndex("DescendantId");

                    b.ToTable("Events");
                });

            modelBuilder.Entity("Repository.Entities.Level", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("LevelName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Sort")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Levels");
                });

            modelBuilder.Entity("Repository.Entities.SiteUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("SiteUsers");
                });

            modelBuilder.Entity("Repository.Entities.YearEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CalenderId")
                        .HasColumnType("int");

                    b.Property<int>("EventId")
                        .HasColumnType("int");

                    b.Property<DateTime>("GregorianDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CalenderId");

                    b.HasIndex("EventId");

                    b.ToTable("YearEvents");
                });

            modelBuilder.Entity("Repository.Entities.Calender", b =>
                {
                    b.HasOne("Repository.Entities.Descendant", "Director")
                        .WithMany()
                        .HasForeignKey("DirectorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Repository.Entities.SiteUser", null)
                        .WithMany("Calenders")
                        .HasForeignKey("SiteUserId");

                    b.Navigation("Director");
                });

            modelBuilder.Entity("Repository.Entities.CalenderUser", b =>
                {
                    b.HasOne("Repository.Entities.Calender", "Calender")
                        .WithMany("CalenderUsers")
                        .HasForeignKey("CalenderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Repository.Entities.Descendant", "Descendant")
                        .WithOne("CalenderUser")
                        .HasForeignKey("Repository.Entities.CalenderUser", "DescendantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Calender");

                    b.Navigation("Descendant");
                });

            modelBuilder.Entity("Repository.Entities.CalenderYear", b =>
                {
                    b.HasOne("Repository.Entities.Calender", "Calender")
                        .WithMany("CalenderYears")
                        .HasForeignKey("CalenderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Calender");
                });

            modelBuilder.Entity("Repository.Entities.Descendant", b =>
                {
                    b.HasOne("Repository.Entities.Descendant", "Father")
                        .WithOne()
                        .HasForeignKey("Repository.Entities.Descendant", "FatherID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Repository.Entities.Descendant", "Mother")
                        .WithOne()
                        .HasForeignKey("Repository.Entities.Descendant", "MotherID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Repository.Entities.SiteUser", "SiteUser")
                        .WithMany("Descendants")
                        .HasForeignKey("SiteUserId");

                    b.HasOne("Repository.Entities.Descendant", "Spouse")
                        .WithOne()
                        .HasForeignKey("Repository.Entities.Descendant", "SpouseID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Father");

                    b.Navigation("Mother");

                    b.Navigation("SiteUser");

                    b.Navigation("Spouse");
                });

            modelBuilder.Entity("Repository.Entities.Event", b =>
                {
                    b.HasOne("Repository.Entities.Calender", "Calender")
                        .WithMany("Events")
                        .HasForeignKey("CalenderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Repository.Entities.Descendant", "Descendant")
                        .WithMany()
                        .HasForeignKey("DescendantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Calender");

                    b.Navigation("Descendant");
                });

            modelBuilder.Entity("Repository.Entities.YearEvent", b =>
                {
                    b.HasOne("Repository.Entities.Calender", "Calender")
                        .WithMany()
                        .HasForeignKey("CalenderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Repository.Entities.Event", "Event")
                        .WithMany()
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Calender");

                    b.Navigation("Event");
                });

            modelBuilder.Entity("Repository.Entities.Calender", b =>
                {
                    b.Navigation("CalenderUsers");

                    b.Navigation("CalenderYears");

                    b.Navigation("Events");
                });

            modelBuilder.Entity("Repository.Entities.Descendant", b =>
                {
                    b.Navigation("CalenderUser");
                });

            modelBuilder.Entity("Repository.Entities.SiteUser", b =>
                {
                    b.Navigation("Calenders");

                    b.Navigation("Descendants");
                });
#pragma warning restore 612, 618
        }
    }
}
